spring:
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**